// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uymlnzyeuvburduuteym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5bWxuenlldXZidXJkdXV0ZXltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzI5OTUsImV4cCI6MjA2NjM0ODk5NX0.LfPN7ulQAahY1JmX-DW-L8BtiTtUkOlMX_3HfK2upxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});